### ISSUE TITLE
有后端代码吗请问

### ISSUE THREAD

**Issue by Lixiaoxing666** [baiziyu-fe/housekeeper-fe#10]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by baiziyu-fe** [comment]
@Lixiaoxing666 这里是对应的后端代码https://github.com/wooyeonicon/house-keeper-company

**Comment by baiziyu-fe** [comment]
give code
