### ISSUE TITLE
寻求课程合作

### ISSUE THREAD

**Issue by specialzxw** [baiziyu-fe/housekeeper-fe#11]
您好，我们对您分享的这个项目很感兴趣，希望可以和您建立联系，根据此项目设计一门课程给同学们学习。在课程完成后，我们将会提供一定的稿费酬劳给到作者，并且课程上线后作者每月还能获得丰厚的收益分成。如果您对我们的邀请有兴趣的话，欢迎添加蓝桥云课官方课程合作微信账号 “shiyanloukecheng” ，了解具体合作详情，期待您的联系～

**Comment by baiziyu-fe** [comment]
> 您好，我们对您分享的这个项目很感兴趣，希望可以和您建立联系，根据此项目设计一门课程给同学们学习。在课程完成后，我们将会提供一定的稿费酬劳给到作者，并且课程上线后作者每月还能获得丰厚的收益分成。如果您对我们的邀请有兴趣的话，欢迎添加蓝桥云课官方课程合作微信账号 “shiyanloukecheng” ，了解具体合作详情，期待您的联系～

---
@specialzxw 您好，我这边非常荣幸收到您的邀请，刚于今日查看邮箱方才得知您的诉求，我们这边正在通过与您的微信进行联系，联系人备注是白子煜，希望能与您一起合作。
